return {
    { q = "The only way to do great work is to love what you do.", a = "Steve Jobs" },
    { q = "Life is what happens to you while you're busy making other plans.", a = "John Lennon" },
    { q = "It is never too late to be what you might have been.", a = "George Eliot" },
    { q = "The future belongs to those who believe in the beauty of their dreams.", a = "Eleanor Roosevelt" },
    { q = "In the middle of difficulty lies opportunity.", a = "Albert Einstein" },
    { q = "The only impossible journey is the one you never begin.", a = "Tony Robbins" },
    { q = "Do what you can, with what you have, where you are.", a = "Theodore Roosevelt" },
    { q = "Happiness depends upon ourselves.", a = "Aristotle" },
    { q = "Everything you can imagine is real.", a = "Pablo Picasso" },
    { q = "Turn your wounds into wisdom.", a = "Oprah Winfrey" },
    { q = "Success is not final, failure is not fatal: it is the courage to continue that counts.", a = "Winston Churchill" },
    { q = "Whether you think you can or you think you can't, you're right.", a = "Henry Ford" },
    { q = "The best way out is always through.", a = "Robert Frost" },
    { q = "Not all those who wander are lost.", a = "J. R. R. Tolkien" },
    { q = "It always seems impossible until it's done.", a = "Nelson Mandela" },
    { q = "Be yourself; everyone else is already taken.", a = "Oscar Wilde" },
    { q = "Excellence, then, is not an act, but a habit.", a = "Will Durant" },
    { q = "What you do speaks so loudly that I cannot hear what you say.", a = "Ralph Waldo Emerson" },
    { q = "The mind is everything. What you think you become.", a = "Buddha" },
    { q = "If you want to lift yourself up, lift up someone else.", a = "Booker T. Washington" },
    { q = "A journey of a thousand miles begins with a single step.", a = "Lao Tzu" },
    { q = "The purpose of our lives is to be happy.", a = "Dalai Lama" },
    { q = "It does not matter how slowly you go as long as you do not stop.", a = "Confucius" },
    { q = "Everything has beauty, but not everyone sees it.", a = "Confucius" },
    { q = "The greatest glory in living lies not in never falling, but in rising every time we fall.", a = "Nelson Mandela" },
    { q = "You miss 100% of the shots you don't take.", a = "Wayne Gretzky" },
    { q = "I have not failed. I've just found 10,000 ways that won't work.", a = "Thomas Edison" },
    { q = "The secret of getting ahead is getting started.", a = "Mark Twain" },
    { q = "It is during our darkest moments that we must focus to see the light.", a = "Aristotle" },
    { q = "Believe you can and you're halfway there.", a = "Theodore Roosevelt" },
    { q = "Act as if what you do makes a difference. It does.", a = "William James" },
    { q = "What lies behind us and what lies before us are tiny matters compared to what lies within us.", a = "Ralph Waldo Emerson" },
    { q = "The only person you are destined to become is the person you decide to be.", a = "Ralph Waldo Emerson" },
    { q = "If opportunity doesn't knock, build a door.", a = "Milton Berle" },
    { q = "You must be the change you wish to see in the world.", a = "Mahatma Gandhi" },
    { q = "A room without books is like a body without a soul.", a = "Marcus Tullius Cicero" },
    { q = "Knowledge is power.", a = "Francis Bacon" },
    { q = "The unexamined life is not worth living.", a = "Socrates" },
    { q = "To be, or not to be, that is the question.", a = "William Shakespeare" },
    { q = "All the world's a stage, and all the men and women merely players.", a = "William Shakespeare" },
    { q = "There is nothing either good or bad, but thinking makes it so.", a = "William Shakespeare" },
    { q = "We know what we are, but know not what we may be.", a = "William Shakespeare" },
    { q = "Some are born great, some achieve greatness, and some have greatness thrust upon them.", a = "William Shakespeare" },
    { q = "Whatever you are, be a good one.", a = "Abraham Lincoln" },
    { q = "Nearly all men can stand adversity, but if you want to test a man's character, give him power.", a = "Abraham Lincoln" },
    { q = "The best thing about the future is that it comes one day at a time.", a = "Abraham Lincoln" },
    { q = "You cannot escape the responsibility of tomorrow by evading it today.", a = "Abraham Lincoln" },
    { q = "Keep your face always toward the sunshine—and shadows will fall behind you.", a = "Walt Whitman" },
    { q = "Do not go where the path may lead, go instead where there is no path and leave a trail.", a = "Ralph Waldo Emerson" },
    { q = "Live in the sunshine, swim the sea, drink the wild air.", a = "Ralph Waldo Emerson" },
    { q = "The only limit to our realization of tomorrow is our doubts of today.", a = "Franklin D. Roosevelt" },
    { q = "When you reach the end of your rope, tie a knot in it and hang on.", a = "Franklin D. Roosevelt" },
    { q = "The future depends on what you do today.", a = "Mahatma Gandhi" },
    { q = "An eye for an eye only ends up making the whole world blind.", a = "Mahatma Gandhi" },
    { q = "Where there is love there is life.", a = "Mahatma Gandhi" },
    { q = "The greatest wealth is to live content with little.", a = "Plato" },
    { q = "Courage is knowing what not to fear.", a = "Plato" },
    { q = "Wise men speak because they have something to say; fools because they have to say something.", a = "Plato" },
    { q = "We are what we pretend to be, so we must be careful what we pretend to be.", a = "Kurt Vonnegut" },
    { q = "And now that you don't have to be perfect, you can be good.", a = "John Steinbeck" },
    { q = "All we have to decide is what to do with the time that is given us.", a = "J. R. R. Tolkien" },
    { q = "Courage is found in unlikely places.", a = "J. R. R. Tolkien" },
    { q = "There is some good in this world, and it's worth fighting for.", a = "J. R. R. Tolkien" },
    { q = "It is our choices that show what we truly are, far more than our abilities.", a = "J. K. Rowling" },
    { q = "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.", a = "J. K. Rowling" },
    { q = "It matters not what someone is born, but what they grow to be.", a = "J. K. Rowling" },
    { q = "After all, tomorrow is another day.", a = "Margaret Mitchell" },
    { q = "Frankly, my dear, I don't give a damn.", a = "Margaret Mitchell" },
    { q = "The only thing we have to fear is fear itself.", a = "Franklin D. Roosevelt" },
    { q = "Ask not what your country can do for you—ask what you can do for your country.", a = "John F. Kennedy" },
    { q = "Those who dare to fail miserably can achieve greatly.", a = "John F. Kennedy" },
    { q = "That's one small step for man, one giant leap for mankind.", a = "Neil Armstrong" },
    { q = "I think, therefore I am.", a = "René Descartes" },
    { q = "The heart has its reasons of which reason knows nothing.", a = "Blaise Pascal" },
    { q = "God is dead.", a = "Friedrich Nietzsche" },
    { q = "That which does not kill us makes us stronger.", a = "Friedrich Nietzsche" },
    { q = "He who has a why to live can bear almost any how.", a = "Friedrich Nietzsche" },
    { q = "One must imagine Sisyphus happy.", a = "Albert Camus" },
    { q = "In the depth of winter, I finally learned that within me there lay an invincible summer.", a = "Albert Camus" },
    { q = "Man is condemned to be free.", a = "Jean-Paul Sartre" },
    { q = "Hell is other people.", a = "Jean-Paul Sartre" },
    { q = "Power tends to corrupt, and absolute power corrupts absolutely.", a = "Lord Acton" },
    { q = "Those who cannot remember the past are condemned to repeat it.", a = "George Santayana" },
    { q = "The pen is mightier than the sword.", a = "Edward Bulwer-Lytton" },
    { q = "If you tell the truth, you don't have to remember anything.", a = "Mark Twain" },
    { q = "Good friends, good books, and a sleepy conscience: this is the ideal life.", a = "Mark Twain" },
    { q = "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", a = "Mark Twain" },
    { q = "Get your facts first, then you can distort them as you please.", a = "Mark Twain" },
    { q = "The journey, not the arrival matters.", a = "T. S. Eliot" },
    { q = "Only those who will risk going too far can possibly find out how far one can go.", a = "T. S. Eliot" },
    { q = "Do not fear death; fear the unlived life.", a = "Natalie Babbitt" },
    { q = "We don't see things as they are, we see them as we are.", a = "Anaïs Nin" },
    { q = "Life shrinks or expands in proportion to one's courage.", a = "Anaïs Nin" },
    { q = "The way to get started is to quit talking and begin doing.", a = "Walt Disney" },
    { q = "If life were predictable it would cease to be life, and be without flavor.", a = "Eleanor Roosevelt" },
    { q = "The future belongs to those who prepare for it today.", a = "Malcolm X" },
    { q = "It is not the years in your life but the life in your years that counts.", a = "Adlai Stevenson" },
    { q = "The only person you should try to be better than is the person you were yesterday.", a = "Anonymous" },
    { q = "Dream big and dare to fail.", a = "Norman Vincent Peale" },
    { q = "Shoot for the moon. Even if you miss, you'll land among the stars.", a = "Norman Vincent Peale" },
    { q = "Change your thoughts and you change your world.", a = "Norman Vincent Peale" },
    { q = "You become what you believe.", a = "Oprah Winfrey" },
    { q = "Doing the best at this moment puts you in the best place for the next moment.", a = "Oprah Winfrey" },
    { q = "The biggest adventure you can take is to live the life of your dreams.", a = "Oprah Winfrey" },
    { q = "You have power over your mind—not outside events. Realize this, and you will find strength.", a = "Marcus Aurelius" },
    { q = "The happiness of your life depends upon the quality of your thoughts.", a = "Marcus Aurelius" },
    { q = "Waste no more time arguing about what a good man should be. Be one.", a = "Marcus Aurelius" },
    { q = "Very little is needed to make a happy life; it is all within yourself.", a = "Marcus Aurelius" },
    { q = "The soul becomes dyed with the color of its thoughts.", a = "Marcus Aurelius" },
    { q = "If it is not right do not do it; if it is not true do not say it.", a = "Marcus Aurelius" },
    { q = "The obstacle is the way.", a = "Marcus Aurelius" },
    { q = "We suffer more often in imagination than in reality.", a = "Seneca" },
    { q = "Luck is what happens when preparation meets opportunity.", a = "Seneca" },
    { q = "Difficulties strengthen the mind, as labor does the body.", a = "Seneca" },
    { q = "It is not that we have a short time to live, but that we waste a lot of it.", a = "Seneca" },
    { q = "He who is brave is free.", a = "Seneca" },
    { q = "Begin at once to live, and count each separate day as a separate life.", a = "Seneca" },
    { q = "Knowing others is intelligence; knowing yourself is true wisdom.", a = "Lao Tzu" },
    { q = "When I let go of what I am, I become what I might be.", a = "Lao Tzu" },
    { q = "Silence is a source of great strength.", a = "Lao Tzu" },
    { q = "Nature does not hurry, yet everything is accomplished.", a = "Lao Tzu" },
    { q = "A good traveler has no fixed plans and is not intent upon arriving.", a = "Lao Tzu" },
    { q = "Mastering others is strength; mastering yourself is true power.", a = "Lao Tzu" },
    { q = "The journey of a thousand miles begins beneath one's feet.", a = "Lao Tzu" },
    { q = "He who knows all the answers has not been asked all the questions.", a = "Confucius" },
    { q = "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.", a = "Confucius" },
    { q = "Our greatest glory is not in never falling, but in rising every time we fall.", a = "Confucius" },
    { q = "Real knowledge is to know the extent of one's ignorance.", a = "Confucius" },
    { q = "Wherever you go, go with all your heart.", a = "Confucius" },
    { q = "Study the past if you would define the future.", a = "Confucius" },
    { q = "The only true wisdom is in knowing you know nothing.", a = "Socrates" },
    { q = "Wonder is the beginning of wisdom.", a = "Socrates" },
    { q = "Be kind, for everyone you meet is fighting a hard battle.", a = "Plato" },
    { q = "Wise men learn more from fools than fools learn from wise men.", a = "Cato the Elder" },
    { q = "It is impossible for a man to learn what he thinks he already knows.", a = "Epictetus" },
    { q = "No man is free who is not master of himself.", a = "Epictetus" },
    { q = "First say to yourself what you would be; and then do what you have to do.", a = "Epictetus" },
    { q = "We have two ears and one mouth so that we can listen twice as much as we speak.", a = "Epictetus" },
    { q = "Don't explain your philosophy. Embody it.", a = "Epictetus" },
    { q = "It's not what happens to you, but how you react to it that matters.", a = "Epictetus" },
    { q = "Knowing yourself is the beginning of all wisdom.", a = "Aristotle" },
    { q = "It is the mark of an educated mind to be able to entertain a thought without accepting it.", a = "Aristotle" },
    { q = "We are what we repeatedly do.", a = "Aristotle" },
    { q = "Pleasure in the job puts perfection in the work.", a = "Aristotle" },
    { q = "The roots of education are bitter, but the fruit is sweet.", a = "Aristotle" },
    { q = "Quality is not an act, it is a habit.", a = "Aristotle" },
    { q = "The energy of the mind is the essence of life.", a = "Aristotle" },
    { q = "Hope is a waking dream.", a = "Aristotle" },
    { q = "Patience is bitter, but its fruit is sweet.", a = "Aristotle" },
    { q = "The beginning is more than half of the whole.", a = "Aristotle" },
    { q = "The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less.", a = "Socrates" },
    { q = "I cannot teach anybody anything. I can only make them think.", a = "Socrates" },
    { q = "An honest man's word is as good as his bond.", a = "Miguel de Cervantes" },
    { q = "The truth may be stretched thin, but it never breaks, and it always surfaces above lies, as oil floats on water.", a = "Don Quixote" },
    { q = "Too much sanity may be madness—and maddest of all: to see life as it is, and not as it should be.", a = "Miguel de Cervantes" },
    { q = "There is no book so bad that something good cannot be found in it.", a = "Miguel de Cervantes" },
    { q = "The greatest wealth is health.", a = "Virgil" },
    { q = "Fortune favors the bold.", a = "Virgil" },
    { q = "Love conquers all.", a = "Virgil" },
    { q = "Time flies.", a = "Virgil" },
    { q = "It is sweet and fitting to die for one's country.", a = "Horace" },
    { q = "Carpe diem.", a = "Horace" },
    { q = "Anger is a brief madness.", a = "Horace" },
    { q = "He who has begun has half done.", a = "Horace" },
    { q = "Every new beginning comes from some other beginning's end.", a = "Seneca" },
    { q = "A smooth sea never made a skilled sailor.", a = "Franklin D. Roosevelt" },
    { q = "Do one thing every day that scares you.", a = "Eleanor Roosevelt" },
    { q = "No one can make you feel inferior without your consent.", a = "Eleanor Roosevelt" },
    { q = "Great minds discuss ideas; average minds discuss events; small minds discuss people.", a = "Eleanor Roosevelt" },
    { q = "It takes as much energy to wish as it does to plan.", a = "Eleanor Roosevelt" },
    { q = "You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.", a = "Eleanor Roosevelt" },
    { q = "A winner is a dreamer who never gives up.", a = "Nelson Mandela" },
    { q = "Education is the most powerful weapon which you can use to change the world.", a = "Nelson Mandela" },
    { q = "A good head and a good heart are always a formidable combination.", a = "Nelson Mandela" },
    { q = "There is no passion to be found playing small and settling for a life that's less than the one you're capable of living.", a = "Nelson Mandela" },
    { q = "I learned that courage was not the absence of fear, but the triumph over it.", a = "Nelson Mandela" },
    { q = "Freedom is never really won. You earn it and win it in every generation.", a = "Coretta Scott King" },
    { q = "Faith is taking the first step even when you don't see the whole staircase.", a = "Martin Luther King Jr." },
    { q = "Darkness cannot drive out darkness; only light can do that.", a = "Martin Luther King Jr." },
    { q = "Injustice anywhere is a threat to justice everywhere.", a = "Martin Luther King Jr." },
    { q = "The time is always right to do what is right.", a = "Martin Luther King Jr." },
    { q = "Life's most persistent and urgent question is, What are you doing for others?", a = "Martin Luther King Jr." },
    { q = "We must accept finite disappointment, but never lose infinite hope.", a = "Martin Luther King Jr." },
    { q = "I have a dream.", a = "Martin Luther King Jr." },
    { q = "You can never cross the ocean until you have the courage to lose sight of the shore.", a = "Christopher Columbus" },
    { q = "The secret of success is to do the common thing uncommonly well.", a = "John D. Rockefeller" },
    { q = "Don't be afraid to give up the good to go for the great.", a = "John D. Rockefeller" },
    { q = "The way to make money is to buy when blood is running in the streets.", a = "John D. Rockefeller" },
    { q = "A friendship founded on business is better than a business founded on friendship.", a = "John D. Rockefeller" },
    { q = "When you undervalue who you are, the world will undervalue what you do.", a = "Oprah Winfrey" },
    { q = "Create the highest, grandest vision possible for your life, because you become what you believe.", a = "Oprah Winfrey" },
    { q = "The greatest discovery of all time is that a person can change his future by merely changing his attitude.", a = "Oprah Winfrey" },
    { q = "You can't use up creativity. The more you use, the more you have.", a = "Maya Angelou" },
    { q = "Try to be a rainbow in someone's cloud.", a = "Maya Angelou" },
    { q = "We may encounter many defeats but we must not be defeated.", a = "Maya Angelou" },
    { q = "Nothing will work unless you do.", a = "Maya Angelou" },
    { q = "My mission in life is not merely to survive, but to thrive.", a = "Maya Angelou" },
    { q = "If you don't like something, change it. If you can't change it, change your attitude.", a = "Maya Angelou" },
    { q = "You are never too old to set another goal or to dream a new dream.", a = "C. S. Lewis" },
    { q = "Courage, dear heart.", a = "C. S. Lewis" },
    { q = "We are what we believe we are.", a = "C. S. Lewis" },
    { q = "There are far, far better things ahead than any we leave behind.", a = "C. S. Lewis" },
    { q = "Humility is not thinking less of yourself, but thinking of yourself less.", a = "C. S. Lewis" },
    { q = "You can make anything by writing.", a = "C. S. Lewis" },
    { q = "Not all who wander are lost.", a = "J. R. R. Tolkien" },
    { q = "All that is gold does not glitter.", a = "J. R. R. Tolkien" },
    { q = "Even the smallest person can change the course of the future.", a = "J. R. R. Tolkien" },
    { q = "The world is full of magic things, patiently waiting for our senses to grow sharper.", a = "W. B. Yeats" },
    { q = "There are no strangers here; Only friends you haven't yet met.", a = "William Butler Yeats" },
    { q = "Think where man's glory most begins and ends, and say my glory was I had such friends.", a = "William Butler Yeats" },
    { q = "Do not wait to strike till the iron is hot; but make it hot by striking.", a = "William Butler Yeats" },
    { q = "The best lack all conviction, while the worst are full of passionate intensity.", a = "William Butler Yeats" },
    { q = "A thing of beauty is a joy forever.", a = "John Keats" },
    { q = "Beauty is truth, truth beauty.", a = "John Keats" },
    { q = "Heard melodies are sweet, but those unheard are sweeter.", a = "John Keats" },
    { q = "Nothing ever becomes real till it is experienced.", a = "John Keats" },
    { q = "The poetry of earth is never dead.", a = "John Keats" },
    { q = "Hope is the thing with feathers that perches in the soul.", a = "Emily Dickinson" },
    { q = "That it will never come again is what makes life so sweet.", a = "Emily Dickinson" },
    { q = "Forever is composed of nows.", a = "Emily Dickinson" },
    { q = "If I can stop one heart from breaking, I shall not live in vain.", a = "Emily Dickinson" },
    { q = "We never know how high we are till we are called to rise.", a = "Emily Dickinson" },
    { q = "I dwell in Possibility.", a = "Emily Dickinson" },
    { q = "The truth is rarely pure and never simple.", a = "Oscar Wilde" },
    { q = "We are all in the gutter, but some of us are looking at the stars.", a = "Oscar Wilde" },
    { q = "Experience is simply the name we give our mistakes.", a = "Oscar Wilde" },
    { q = "Always forgive your enemies; nothing annoys them so much.", a = "Oscar Wilde" },
    { q = "To live is the rarest thing in the world. Most people exist, that is all.", a = "Oscar Wilde" },
    { q = "Life is far too important a thing ever to talk seriously about.", a = "Oscar Wilde" },
    { q = "We are each our own devil, and we make this world our hell.", a = "Oscar Wilde" },
    { q = "It is absurd to divide people into good and bad. People are either charming or tedious.", a = "Oscar Wilde" },
    { q = "The only duty we owe to history is to rewrite it.", a = "Oscar Wilde" },
    { q = "There is no such thing as a moral or an immoral book. Books are well written, or badly written.", a = "Oscar Wilde" },
    { q = "We have really everything in common with America nowadays except, of course, language.", a = "Oscar Wilde" },
    { q = "All happy families are alike; each unhappy family is unhappy in its own way.", a = "Leo Tolstoy" },
    { q = "Everyone thinks of changing the world, but no one thinks of changing himself.", a = "Leo Tolstoy" },
    { q = "If you want to be happy, be.", a = "Leo Tolstoy" },
    { q = "The two most powerful warriors are patience and time.", a = "Leo Tolstoy" },
    { q = "Without knowing what I am and why I am here, life is impossible.", a = "Leo Tolstoy" },
    { q = "Boredom: the desire for desires.", a = "Leo Tolstoy" },
    { q = "The strongest of all warriors are these two—Time and Patience.", a = "Leo Tolstoy" },
    { q = "It is amazing how complete is the delusion that beauty is goodness.", a = "Leo Tolstoy" },
    { q = "Everything I know, I know only because of love.", a = "Leo Tolstoy" },
    { q = "All, everything that I understand, I understand only because I love.", a = "Leo Tolstoy" },
    { q = "You have to know how to accept rejection and reject acceptance.", a = "Ray Bradbury" },
    { q = "You must stay drunk on writing so reality cannot destroy you.", a = "Ray Bradbury" },
    { q = "Without libraries what have we? We have no past and no future.", a = "Ray Bradbury" },
    { q = "There is no end to education. It is not that you read a book, pass an examination, and finish with education.", a = "Isaac Asimov" },
    { q = "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.", a = "Isaac Asimov" },
    { q = "People who think they know everything are a great annoyance to those of us who do.", a = "Isaac Asimov" },
    { q = "Violence is the last refuge of the incompetent.", a = "Isaac Asimov" },
    { q = "Any sufficiently advanced technology is indistinguishable from magic.", a = "Arthur C. Clarke" },
    { q = "The only way of discovering the limits of the possible is to venture a little way past them into the impossible.", a = "Arthur C. Clarke" },
    { q = "Two possibilities exist: either we are alone in the Universe or we are not. Both are equally terrifying.", a = "Arthur C. Clarke" },
    { q = "The future isn't what it used to be.", a = "Arthur C. Clarke" },
    { q = "The answer to the ultimate question of life, the universe and everything is 42.", a = "Douglas Adams" },
    { q = "Don't Panic.", a = "Douglas Adams" },
    { q = "I love deadlines. I love the whooshing noise they make as they go by.", a = "Douglas Adams" },
    { q = "Time is an illusion. Lunchtime doubly so.", a = "Douglas Adams" },
    { q = "Human beings, who are limited by biology, don't have the power to fully understand anything.", a = "Douglas Adams" },
    { q = "The most important thing we learn at school is the fact that the most important things can't be learned at school.", a = "Haruki Murakami" },
    { q = "Pain is inevitable. Suffering is optional.", a = "Haruki Murakami" },
    { q = "If you only read the books that everyone else is reading, you can only think what everyone else is thinking.", a = "Haruki Murakami" },
    { q = "Memories warm you up from the inside. But they also tear you apart.", a = "Haruki Murakami" },
    { q = "When you come out of the storm, you won't be the same person who walked in.", a = "Haruki Murakami" },
    { q = "What we think, we become.", a = "Buddha" },
    { q = "Three things cannot be long hidden: the sun, the moon, and the truth.", a = "Buddha" },
    { q = "Peace comes from within. Do not seek it without.", a = "Buddha" },
    { q = "Holding on to anger is like drinking poison and expecting the other person to die.", a = "Buddha" },
    { q = "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", a = "Buddha" },
    { q = "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path.", a = "Buddha" },
    { q = "The trouble is, you think you have time.", a = "Buddha" },
    { q = "What you seek is seeking you.", a = "Rumi" },
    { q = "The wound is the place where the Light enters you.", a = "Rumi" },
    { q = "Let yourself be silently drawn by the strange pull of what you really love.", a = "Rumi" },
    { q = "Don't grieve. Anything you lose comes round in another form.", a = "Rumi" },
    { q = "The quieter you become, the more you are able to hear.", a = "Rumi" },
    { q = "Raise your words, not your voice. It is rain that grows flowers, not thunder.", a = "Rumi" },
    { q = "Live as if you were to die tomorrow. Learn as if you were to live forever.", a = "Mahatma Gandhi" },
    { q = "Be the change that you wish to see in the world.", a = "Mahatma Gandhi" },
    { q = "The weak can never forgive. Forgiveness is the attribute of the strong.", a = "Mahatma Gandhi" },
    { q = "Strength does not come from physical capacity. It comes from an indomitable will.", a = "Mahatma Gandhi" },
    { q = "Hate the sin, love the sinner.", a = "Mahatma Gandhi" },
    { q = "Earth provides enough to satisfy every man's needs, but not every man's greed.", a = "Mahatma Gandhi" },
    { q = "An ounce of prevention is worth a pound of cure.", a = "Benjamin Franklin" },
    { q = "Tell me and I forget, teach me and I remember, involve me and I learn.", a = "Benjamin Franklin" },
    { q = "Well done is better than well said.", a = "Benjamin Franklin" },
    { q = "Either write something worth reading or do something worth writing.", a = "Benjamin Franklin" },
    { q = "Lost time is never found again.", a = "Benjamin Franklin" },
    { q = "He that can have patience can have what he will.", a = "Benjamin Franklin" },
    { q = "Diligence is the mother of good luck.", a = "Benjamin Franklin" },
    { q = "Energy and persistence conquer all things.", a = "Benjamin Franklin" },
    { q = "By failing to prepare, you are preparing to fail.", a = "Benjamin Franklin" },
    { q = "An investment in knowledge pays the best interest.", a = "Benjamin Franklin" },
    { q = "If you would know the value of money, go and try to borrow some.", a = "Benjamin Franklin" },
    { q = "Beware of little expenses. A small leak will sink a great ship.", a = "Benjamin Franklin" },
    { q = "You may delay, but time will not.", a = "Benjamin Franklin" },
    { q = "A penny saved is a penny earned.", a = "Benjamin Franklin" },
    { q = "The harder I work, the luckier I get.", a = "Samuel Goldwyn" },
    { q = "The best revenge is massive success.", a = "Frank Sinatra" },
}